### PR TITLE
Refactor(all): Create "lib" workspace

### PR DESCRIPTION
**Pull request by thien-do**
"lib" is a workspace that consists of the previous "core", "gallery", and "docs" projects.

**Why:** the initial target is for contributors to quickly have a local development env, as simple as running `yarn start`

At first, this is quite simple: we only need to prepend the install before the actual start, like from `start: start-storybook` to `start: yarn && start-storybook`.

However, this faced a challenge, that "docs", intentionally, does not use "core" and "gallery" on npm, but link directly to their source code (i.e. in "docs" there are imports like "../../core/src"). This allows a fast iteration in local dev, with proper TS compiling and postcss processing. So, our previous solution, is to trigger the "install" of "core" and "gallery" in a "postinstall" script at "docs". Something like:

```
postinstall: "cd ../core && yarn && cd ../gallery && yarn
```

However, this has a risky issue: "core", "gallery" and "docs" now may have different instances of a same dependency (e.g. react), because each has its own node_modules:

```
core/
- node_modules
  - react@17.0.1
gallery/
- node_modules
  - react@17.0.1
docs/
- node_modules
  - react@17.0.1
```

so, for example, the Button in "core" imports "/core/node_modules/react", but the Shot in gallery imports "/gallery/node_modules/react". This is problematic if they interact with each other (due to React's internal state for hooks).

So, the final solution, is to use yarn workspace to hoist dependencies **BUT without linking our projects**. Why not linking our projects? Because we still want "docs" to use the "source" of other projects, and not the built assets (i.e. "dist").

Using yarn workspace means that the same dependencies get hoisted like this:

```
lib/
- node_modules
  - react@17.0.1
- core/
- docs/
- gallery/
```

Which means core, docs and gallery all use the same instance of react!

This is not completely bullet-proof, actually, as if we define an incompatible version somewhere, that version will be put in its project's node_modules, and thus still causing different instances. But at least, with this setup, it would be easier to see this situation.

### CODE REVIEW

**Comment by thien-do** [comment]
@ng-hai you may notice that the dependencies are no longer use "exact" version but a more loosely one. This is intended to help the hoisting easier (i.e. more dependencies can be hoisted)


image

**Comment by thien-do** [comment]
Btw the linting is failing because I moved tsconfig to "lib", which is wrong. It should stay in root for the lint to read it

**Review by ng-hai — APPROVED** [review]
Looks like the next step will be Lerna acquirement soon 😄

**Comment by thien-do** [comment]
No! I will NEVER use Lerna!

Joke, that was what I said about yarn and storybook back then =))

**Pull request merged**
